In [21]:
import numpy as np
import pandas as pd

pd.set_option('max_columns', None)
pd.set_option('max_colwidth', None)

df_heart = pd.DataFrame()
df_heart = pd.read_csv('Heart.csv')
df_heart

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [22]:
from sklearn.model_selection import train_test_split
feature_cols = ['Age','RestingBP','Cholesterol','FastingBS',
                'MaxHR','Oldpeak']

X = df_heart[feature_cols]
y = df_heart['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35,random_state=3)

In [23]:
from sklearn.linear_model import LinearRegression
#creating new linear regression model
my_lin_reg = LinearRegression()
my_lin_reg.fit(X_train,y_train)

y_pred = my_lin_reg.predict(X_test)

print(y_pred)

[0.51546761 0.90864042 0.92661367 0.71555285 0.28537627 0.74808572
 1.19845873 0.63933482 0.18948378 0.47400626 0.51404472 0.35606697
 0.09401281 0.5130336  0.96965375 0.26227035 0.7918731  0.8353823
 0.62040089 0.48588508 0.4783493  0.707684   1.26517203 0.47524399
 0.25559739 0.46136863 0.78005999 0.56341175 0.13543843 0.86032898
 1.02213041 0.47804435 0.8826805  0.30717404 0.31396129 0.2379532
 1.1502708  0.38343438 0.45988447 1.02693575 0.81163999 0.7038657
 0.26114513 0.7158743  0.30158801 0.87884072 0.66938778 0.33542494
 0.16692092 0.4943058  0.59923402 0.83312611 0.80889091 0.15777085
 0.53428181 0.63880985 0.2958788  0.21251713 0.6789037  0.60527117
 0.16952519 0.80054768 0.29408137 0.76835643 0.69208747 0.14629234
 0.47814911 1.01595283 0.35987259 0.67983904 0.3083624  0.28812019
 0.34078546 0.59303192 0.58320542 0.29893279 0.81905845 0.71377353
 0.24131349 0.40758407 1.11275921 0.46125189 0.874547   0.61353115
 0.25343762 0.69198557 0.45077129 0.70968417 0.31203397 0.41815851
 0.05309953 0.88723294 0.57499763 0.52708229 0.61706239 0.75165739
 0.25033304 0.22284728 0.60549362 0.50816376 0.94571124 0.42075933
 1.28209501 0.7707781  0.32521602 0.6789868  0.68212595 0.63984833
 0.69641423 0.27587721 1.04316559 0.98634258 0.52819229 0.15006423
 0.52579126 0.41449175 0.44266335 0.22674097 1.03268027 0.29809005
 0.58038966 0.78588958 0.4308342  0.5898701  0.34901191 0.48938585
 0.40428621 0.20370217 0.10133357 0.11271592 0.64553157 0.49271767
 0.25783688 0.76010765 0.36543058 1.01205011 0.5099218  0.41667348
 0.49490867 0.7252082  1.01148619 0.30856775 0.24556944 0.4745711
 0.73819036 0.09119807 0.36608836 0.20507877 0.54774007 0.8231862
 0.84388155 0.73312997 0.7278262  0.50971701 0.32608822 0.5360779
 0.92202041 0.96854637 0.35115584 0.89956116 0.38860768 0.33336706
 0.1457267  1.14154789 0.47120018 0.62291934 0.42592184 0.51312655
 0.81232495 0.27824381 0.79659038 0.19522832 0.91586888 0.58916697
 0.15699621 0.46202844 0.22499356 0.61428838 0.59534776 0.5223262
 0.25910831 0.69330417 0.53866847 0.62136846 0.56339097 0.40237804
 1.0132063  0.55959065 0.35435049 0.5813475  1.03506595 0.71122852
 0.16979711 0.66579034 0.56705677 0.37240856 0.36477001 0.11680965
 0.75655121 0.70588039 0.9728978  0.2416242  0.78691481 0.6711059
 0.6391014  0.54206458 0.98826    0.30015518 0.69864354 0.46958669
 0.57969682 0.17790672 0.24503205 0.85128771 0.54739933 0.26405706
 0.5219706  0.22362088 0.74792611 0.5273301  0.49002303 0.64091221
 0.72463212 0.21634864 0.43562949 0.95194405 0.84518849 0.46992734
 0.45952026 0.72708189 0.54799619 0.78125615 0.72613353 0.49047946
 0.71906176 0.29327134 0.39097454 1.0331529  0.50309015 0.57171989
 0.4265052  0.29094558 0.70220358 0.64555516 0.38312045 0.33707659
 1.08232737 0.55031231 0.44010788 0.41086472 0.83620175 0.9726111
 0.71077076 0.70283081 0.67129689 0.73540001 0.76902478 0.33972681
 0.6894508  0.97904222 1.03234833 0.59766442 0.44598249 0.10908753
 0.49535072 0.72880607 0.30976727 0.35791245 0.4677918  0.79602822
 0.57324517 0.52900596 0.30453423 0.1554432  1.02865109 0.74850971
 0.33784201 0.78563868 0.96454695 0.63251697 0.1934297  0.89430968
 1.15856709 0.78949287 0.98543039 0.25468877 0.1296595  0.43666006
 0.58595494 0.93054786 0.95125331 0.47179828 0.27102692 0.50025525
 0.6616524  0.27043421 0.63094921 0.11928237 1.23697275 0.55875127
 0.7016854  0.74655746 0.7535981  0.25196918 0.25693937 0.70027019
 0.42160877 0.56014507 0.70934844 0.97540259 0.92631913 0.62568175
 0.18713146 1.00173969 0.41100796 0.2864069  0.64939993 0.30738469
 0.49355513 0.29018884 0.24775782 0.82043436]

In [24]:
from sklearn import metrics
#calculating mse
mse = metrics.mean_squared_error(y_test, y_pred)
mse

0.1547578933755646

In [25]:
#calculating rmse(accuracy score)
rmse = np.sqrt(mse)
print('Below is our accuracy score before applying One Hot Coding:')
print(rmse)
print('Unlike other methods we use RMSE as our accuracy score. The lower the number for RMSE the better. \nThink of RMSE being the chances that the prediction is wrong, meaning having a .39 RMSE means that \nour accuracy score would be .59')

Below is our accuracy score before applying One Hot Coding:
0.39339279781862374
Unlike other methods we use RMSE as our accuracy score. The lower the number for RMSE the better.
Think of RMSE being the chances that the prediction is wrong, meaning having a .39 RMSE means that
our accuracy score would be .59

In [26]:
print('We will now be applying One Hot Coding')

We will now be applying One Hot Coding

In [27]:
#applying One Hot Coding
sex_dum = pd.get_dummies(df_heart.Sex)
cpt_dum = pd.get_dummies(df_heart.ChestPainType)
recg_dum = pd.get_dummies(df_heart.RestingECG)
ea_dum = pd.get_dummies(df_heart.ExerciseAngina)
sts_dum = pd.get_dummies(df_heart.ST_Slope)
OHC_df = pd.concat([df_heart, sex_dum, cpt_dum, recg_dum, ea_dum, sts_dum], axis='columns')
#new df with OHC applied
OHC_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,F,M,ASY,ATA,NAP,TA,LVH,Normal,ST,N,Y,Down,Flat,Up
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,1,0,0,0,1,0,0,1,0,1,0,0,1,0
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,0,1,0,1,0,0,0,0,1,1,0,0,0,1
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,1,0,1,0,0,0,0,1,0,0,1,0,1,0
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,0,1,0,0,0,1,0,1,0,1,0,0,1,0
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0,1,1,0,0,0,0,1,0,1,0,0,1,0
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,0,1,1,0,0,0,0,1,0,0,1,0,1,0
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1,1,0,0,1,0,0,1,0,0,1,0,0,1,0
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1

In [28]:
#new feature columns to fit with One Hot Coding
new_feature_cols = ['Age','RestingBP','Cholesterol','FastingBS','MaxHR',
                    'Oldpeak','F','M','ASY','ATA','NAP','TA','LVH',
                    'Normal','ST','N','Y','Down','Flat','Up']
D = OHC_df[new_feature_cols]
e = OHC_df['HeartDisease']
#splitting the new data
D_train, D_test, e_train, e_test = train_test_split(D, e, test_size=0.35,random_state=3)

In [29]:
#creating new linear regression model
linreg = LinearRegression()
linreg.fit(D_train,e_train)

y_prediction = linreg.predict(D_test)

print(y_prediction)

[ 8.40670785e-01  7.83217401e-01  8.13098842e-01  9.17723383e-01
  1.68093725e-01  9.86876027e-01  1.14813104e+00  6.79559455e-01
  8.96985587e-02  3.39596677e-01  2.68122605e-01  2.21646031e-01
 -1.29747802e-01  6.51577348e-01  1.27150356e+00 -8.90295212e-02
  9.88345944e-01  9.21558320e-01  8.72899628e-01  6.34174370e-01
  5.85836766e-01  8.34226451e-01  9.51064316e-01  7.95907242e-01
  3.66240137e-01  8.50449468e-01  8.79422165e-01  2.92334320e-01
  6.73007769e-02  1.11100085e+00  1.03181003e+00  5.11745221e-01
  1.03225177e+00 -8.26781566e-02  4.66270034e-01 -1.72546675e-01
  1.14039826e+00  9.08705175e-02  8.52058137e-01  5.19372494e-01
  9.70327341e-01  1.02752180e+00  1.21407723e-01  2.92853504e-01
 -4.68750332e-02  8.66550011e-01  6.40940698e-01  3.70364579e-01
  3.85403140e-01  9.21850620e-01  9.24701656e-01  7.67706175e-01
  7.38086971e-01 -8.29119185e-02  5.60472672e-01  9.34817514e-01
 -4.73783027e-02  2.76113520e-01  9.75888442e-01  5.61021279e-01
 -9.00699295e-02  7.46162639e-01  1.36636983e-01  1.01177206e+00
  5.90673162e-01 -7.69324097e-02  1.59255581e-01  8.60535767e-01
 -2.39204092e-02  5.78536660e-01  3.75084841e-01 -1.12517580e-01
 -8.38211369e-02  8.88187355e-01  4.54836772e-01 -1.34670289e-01
  1.04022274e+00  8.93660544e-01  3.48239364e-01  1.14815650e-01
  1.11037004e+00  5.56123140e-01  6.66937447e-01  6.66878836e-01
  5.60432244e-02  6.53074166e-01  4.56295201e-01  9.22560459e-01
  9.00950695e-02  3.42250387e-01  3.15332391e-02  9.14426956e-01
  3.47164215e-01  2.67657019e-02  7.35870149e-01  8.25141793e-01
  2.72089857e-01  3.48064482e-01  3.76640024e-01  2.48569254e-01
  1.11489163e+00  6.08364663e-01  1.10922980e+00  4.02478508e-01
  8.26170738e-02  9.43453945e-01  8.10159575e-01  9.09946559e-01
  9.56005227e-01  2.70774988e-01  1.15093454e+00  1.05275226e+00
  3.83749440e-01 -1.26036630e-01 -3.26062441e-02  5.27516872e-01
  1.83308191e-01  1.01504630e-01  1.11341262e+00 -1.37612083e-01
  9.49164511e-01  9.34990274e-01  2.12792715e-01  1.58426181e-01
 -3.70477579e-02  7.38180718e-01  3.81302873e-01  8.82254786e-02
 -9.11013454e-02 -1.44669327e-01  9.46174773e-01  3.78804332e-01
  8.13782565e-02  9.01679090e-01 -1.12235006e-01  1.00947937e+00
  9.18554541e-01  4.12282202e-01  8.47911460e-03  7.30470382e-01
  7.81756158e-01  1.50868516e-01  1.22436807e-01  3.41861636e-01
  9.94352852e-01 -1.61189565e-04  5.89620091e-01  1.76422884e-01
  6.16327501e-01  8.17572940e-01  1.01597611e+00  9.32180303e-01
  9.65686734e-01  4.06683797e-01  3.46983214e-01  1.96752701e-01
  7.96923907e-01  7.47871746e-01  2.28457579e-01  9.91423854e-01
  2.51565453e-01  2.92860470e-01  1.05272628e-01  1.08237809e+00
  3.92135871e-01  9.05045310e-01  3.04046151e-01  1.17773452e-01
  8.20445523e-01  3.70592437e-01  1.02047607e+00  6.20470670e-01
  1.06569073e+00  5.37897127e-01  2.95087560e-01  1.58061783e-01
  7.46518320e-01  4.56419252e-01  9.38976341e-01  5.40054188e-01
  2.23175670e-01  8.86856500e-01  1.29042707e-01  4.48430987e-01
  8.96371595e-01  6.02747448e-01  1.05453135e+00  1.23633737e-01
  4.49248884e-01  9.18814787e-01  1.00909440e+00  8.46643516e-01
  6.56410253e-01  9.29043013e-01  6.72512159e-01  4.20772593e-01
  3.89059759e-01 -7.06327275e-03  8.61443527e-01  4.54778892e-01
  1.12827591e+00  8.98254490e-02  9.50003409e-01  3.35647614e-01
  1.01489634e+00  7.77680498e-01  8.93295246e-01  3.27823936e-01
  9.58650956e-01  7.39732740e-01  8.44592960e-01  3.95122020e-01
  1.12207151e-01  7.33989247e-01  2.88022718e-01  9.07628268e-02
  4.94826748e-01  1.25897977e-01  8.26920559e-01  9.84683726e-02
  2.91416305e-01  3.30066529e-01  8.47785967e-01  7.20083340e-02
  1.73322691e-01  9.85006701e-01  8.98909051e-01  2.28961785e-01
  6.85888559e-01  7.39370909e-01  7.05502448e-01  8.87093886e-01
  9.15354369e-01  1.62329522e-01  6.64211688e-01 -6.07768187e-02
  7.09832045e-01  1.18824150e+00  8.70575958e-01  5.84096346e-01
  2.37533316e-01  1.73052108e-01  8.67943979e-01  9.39449027e-01
  1.44322328e-01  4.57709247e-01  7.85951409e-01  5.10333601e-01
  3.19926178e-01  7.85867059e-01  1.07811234e+00  9.02620897e-01
  7.27468519e-01  7.41771822e-01  8.83284018e-01  9.68924517e-01
  9.74754207e-01  7.27489337e-01  7.07085669e-01  9.41690916e-01
  6.33207074e-01  1.91240482e-01  6.13654235e-01  1.20829381e-01
  2.73495006e-01  7.15010994e-01  3.44570127e-01  2.82806925e-01
  1.40701310e-01  9.58380809e-01  8.47272497e-01  2.63954032e-01
 -1.42909570e-01  1.34489382e-02  7.96117260e-01  6.43965103e-01
  5.89343765e-01  5.95034276e-01  8.69622474e-01  5.42622151e-01
  3.63704732e-02  6.74071130e-01  1.05555258e+00  8.76650824e-01
  1.09255557e+00  2.91991268e-01  1.15738242e-01  5.66753752e-01
  3.63472121e-01  1.14720429e+00  8.80701786e-01  7.19540182e-01
  3.15907193e-01  5.58799089e-01  1.01423961e+00  2.75929993e-01
  7.48994616e-01  6.24122559e-01  1.01534305e+00  5.00872665e-01
  8.68416001e-01  9.18230375e-01  3.43390377e-01 -1.60071489e-01
  6.94109442e-01  1.06184606e+00  1.14504137e-01  8.82303818e-01
  7.82065213e-01  9.72399035e-01  1.10486125e+00  9.85280597e-01
 -1.58803808e-01  1.02507720e+00  7.87003555e-01  9.71170421e-02
  5.72433536e-01  1.73969135e-01 -2.07654713e-02  1.24167404e-01
 -1.01782980e-01  7.54247839e-01]

In [30]:
#calculating mse
OHC_mse = metrics.mean_squared_error(e_test, y_prediction)
OHC_mse

0.09220795675222586

In [31]:
#Calculating rmse
OHC_rmse = np.sqrt(mse)
print('RMSE for data frame with One Hot Coding:')
print(OHC_rmse)

RMSE for data frame with One Hot Coding:
0.39339279781862374

In [32]:
print('As we can see the RMSE is the same for both before and after applying One Hot Coding for the linear regression model')

As we can see the RMSE is the same for both before and after applying One Hot Coding for the linear regression model